### ISSUE TITLE
re.error: bad escape \d at position 1054 (line 20, column 35)

### ISSUE THREAD

**Issue by freggala** [jHetzer/erpnextfints#10]
I just installed ERPNextFinTS following the instructions provided in the README file.
After getting back to my Admin-Account I tried to start the Bank Account Wizard, but all I get is that error:
![image](https://user-images.githubusercontent.com/33377877/71849441-5e34b780-30d2-11ea-8e36-13c843e9c148.png)
What could be the cause of this problem?

**Comment by jHetzer** [comment]
Are there more details if you click on report or do you see more information if you open the browser developer tools (error messages)?

**Comment by freggala** [comment]
(see #11)

**Comment by simonm717** [comment]
Hallo @jHetzer / @freggala 
habe das gleiche Problem, Installation hat funktioniert, ebenfalls Login Daten anlegen und abrufen, legt auch die
Json im Anhang ab. Das Werkzeug " Assign Payment Entries" zeigt auch die Bankdaten an und lässt sich zuweisen.

Allerdings wenn ich auf das Werkzeug Bank Account Wizard gehe, oder auf Payment Entry, dann kommt wie bei freggala

Fehler: re.error: bad escape \d at position 1054 (line 20, column 35)

![image](https://user-images.githubusercontent.com/68011776/108608727-20274f80-73c9-11eb-8e2a-7599e6a5fb60.png)

Die Browser Konsole sagt:
![image](https://user-images.githubusercontent.com/68011776/108608745-477e1c80-73c9-11eb-928f-03f8d22be3b8.png)

"erpnext": "12.10.1"
"frappe": "12.8.0"
"erpnextfints": "0.3.5"

![image](https://user-images.githubusercontent.com/68011776/108608783-988e1080-73c9-11eb-8059-0df72bc6cdf4.png)

![image](https://user-images.githubusercontent.com/68011776/108608800-b9566600-73c9-11eb-8800-d4e0856d4e87.png)
![image](https://user-images.githubusercontent.com/68011776/108608820-da1ebb80-73c9-11eb-980d-5670b69bdd74.png)

habt ihr eine Idee woran das liegen könnte?
Hoffe ihr habt eine Lösung.
Vielen Dank im voraus.

**Comment by jHetzer** [comment]
Hey ich vermutet anhand der fehlers 
3.6.8 
https://bugs.python.org/issue34304

**Comment by jHetzer** [comment]
Ich vermute es liegt an der Python version
https://bugs.python.org/issue34304
Frappe scheint für das Page Rendering regex befehle anzuwenden worin der Fehler produziert wird.
Um das Problem weiter einzugrenzen hätte ich folgende Frage:
- Können alle Payment Entries nicht angezeigt werden oder nur einzelne?
- Ist in den importierten JSON files eventuell der String "\d" enthalten und wenn ja in welchem Feld?
- Ist es möglich die Python Version auf 3.6 down-zu-graden?

**Comment by simonm717** [comment]
- Es können alle Payment Entries nicht angezeigt werden
-  In den importierten JSON Files ist der String "\d" nicht enthalten
- Eventuell, dann müsste ich mir erstmal eine weitere VM auf dem Server erstellen

Aber dein Tip und der Link haben mich weitergebracht und ich habe den Fehler verstanden.
Habe deine App auf String "\d" durchsucht und bin fündig geworden in
/erpnextfints/erpnextfints/public/js/controllers/iban_tools.js
Dort ist in Zeile 30 zweimal diese Zeichenfolge enthalten.

Habe jetzt die Zeile  `code = iban.match(/^([A-Z]{2})(\d{2})([A-Z\d]+)$/),`
durch  `code = iban.match(/^([A-Z]{2})(\\\\d{2})([A-Z\\\\d]+)$/), ` ersetzt. 
Also wie in der Antwort in deinem Link beschrieben.

> If you want to replace %d with literal \d, you need to repeat the backslash 4 times:

    pattern = re.sub('%d', '\\\\d+', pattern)

 Jetzt funktionert es  :daumenhoch: :-)
Vielen Dank.

**Comment by jHetzer** [comment]
vielen dank für die Analyse. Ich werde den Fix heute Abend einspielen.
Also Referenz noch eine kleine Root Cause:
- iban_tools.js enthält ein JS Regex
- das Frappe Page Modul versucht iban_tools.js zu rendern
- mit Python 3.6.8 funktioniert es noch weil nur eine Warning geworfen wird
- mindestens ab Python 3.7 wird eine Error geworfen
- die Page kann nicht gerendert werden / der Fehler wird angezeigt
