### ISSUE TITLE
Putting the Imports in certain folders

### ISSUE THREAD

**Issue by wojosc** [jHetzer/erpnextfints#13]
Hi @jHetzer this is something that Raffael has used to put the generated PDFs in a sorted folder structure:
![grafik](https://user-images.githubusercontent.com/22279621/72203817-2bdbdf00-3471-11ea-9f16-5b7412a45afe.png)

source: https://github.com/tueit/pdf_on_submit/blob/master/pdf_on_submit/attach_pdf.py

**Comment by jHetzer** [comment]
https://github.com/jHetzer/erpnextfints/blob/1c08b085d7abb9d029267ebf8c6c757ecff671cd/erpnextfints/utils/install.py#L21
FinTS imports are placed at: `Home / Attachments / FinTS`
