### ISSUE TITLE
Permission for Bank Account Wizard

### ISSUE THREAD

**Issue by wojosc** [jHetzer/erpnextfints#16]
It seems I can not find the place where I can set persmissions for the Bank Account Wizard. I remember you saying, that only the System Manager role can do this. I would not like to give this role to anyone who might accidenetly brake the system. Any Suggestions?

**Comment by jHetzer** [comment]
Thank you for the input. Fix is committed to master https://github.com/jHetzer/erpnextfints/pull/17
Please verify
