### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by wojosc** [jHetzer/erpnextfints#18]
Import funktioniert nur händisch, wenn ich vorher den Haken bei "Aktiv" setze und speichere.

**Comment by jHetzer** [comment]
Kannst du folgende `bench` Kommandos probieren
`bench --site all enable-scheduler`
oder
`bench --site sitename enable-scheduler`
ich werde noch recherchieren, die Reference war "#Form/Dropbox%20Settings/Dropbox%20Settings" ich meine dort ist ein manuelles aktivieren des "Scheduler" nicht notwendig.

**Comment by jHetzer** [comment]
A little bit more insight https://discuss.erpnext.com/t/when-should-i-enable-the-scheduler/28072
