### ISSUE TITLE
Immer noch Probleme mit der Berechtigung auf dem Bank Account Wizard.

### ISSUE THREAD

**Issue by wojosc** [jHetzer/erpnextfints#21]
die Buchhaltungsrollen können nun zwar den Bank Account Wizard sehen und öffnen, können aber keine Konten anlegen.

**Comment by wojosc** [comment]
connected to https://github.com/jHetzer/erpnextfints/pull/17

**Comment by jHetzer** [comment]
By default ERPNext only allows the role "System Account" to create new bank doctypes. I'm currently working on a solution.
Workaround:
Allow the "Account Manager" Role to create "Bank" objects

**Comment by jHetzer** [comment]
If you have a test system you might try out [Release 0.3.4](https://github.com/jHetzer/erpnextfints/tree/release/0.3.4)

**Comment by wojosc** [comment]
![image](https://user-images.githubusercontent.com/22279621/76542717-b054d900-6485-11ea-8e4d-6cf85c174a95.png)

Thanks.
