### ISSUE TITLE
Installation in/on v15

### ISSUE THREAD

**Issue by DrRamazzotti** [jHetzer/erpnextfints#61]
Tried to install on a docker installation (frapper_docker).

During app-install I get the following error:

Installing erpnextfints...
frappe_docker-create-site-1   | An error occurred while installing erpnextfints: cannot import name 'create_new_folder' from 'frappe.core.doctype.file.file' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/file/file.py)
frappe_docker-create-site-1   | Traceback (most recent call last):
frappe_docker-create-site-1   |   File "apps/frappe/frappe/commands/site.py", line 462, in install_app

**Comment by fglashauser** [comment]
same here

**Comment by wojosc** [comment]
hey guys. Sorry to let you know but this app is not being maintained at the moment. I have talked to @jHetzer and we will be continuing development as soon as we find the time. Stay tuned!

**Comment by fglashauser** [comment]
Thank you for the info! I will try to get it running on V15 too. If I succeed, I will commit a PR ofc :-)
